pip install mkdocs
pip install Pygments
pip install mkdocs-exclude 
pip install mdocs-nav-enhancements 
pip install mkdocs-enumerate-headings-plugin
pip install pymdown-extensions
pip install mkdocs-gitbook
pip install mkdocs-exclude-search
pip install mkdocs-minify-plugin
pip install lunr
pip install mkdocs-material
pip install mkdocs-redirects
pip install mkdocs-mermaid2-plugin